name: Build and Publish Services

on:
  push:
    branches: [ "test-branch" ]

jobs:
  build-and-publish-services:
    runs-on: ubuntu-latest
    container:
          image: maven:3.9.6-eclipse-temurin-17
    steps:
      - name: Run Common Workflow for Services
        uses: zodgevaibhav/github-action-learn/.github/workflows@test-branch
        with:
          service_name: 'services/auth'
