name: Build and Publish Plugins

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  build-and-publish-plugins:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: ['plugins/my-plugin']

    needs: common

    steps:
      - name: Run Common Workflow for Plugins
        uses: ./.github/workflows/common-build.yml
        with:
          module: ${{ matrix.module }}
