name: Build and Publish Common Workflow

on:
  push:
    branches:
      - main
      - 'services/**'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - services/auth

    container:
      image: maven:3.9.6-eclipse-temurin-17
    steps:
      - uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn -f ${{ matrix.service }}/pom.xml clean install

      - name: Lint Check (Replace with your linting command)
        run: |
          echo "Performing lint check..."
          # Add your linting command here

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
      #          docker build -t ${{ matrix.service }}:latest ${{ matrix.service }}
      - name: Log in to Nexus Repository
        run: |
          echo "Logging in to Nexus..."
      #          docker login -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }} your-nexus-repository-url
      - name: Push Docker Image to Nexus
        run: |
          echo "Pushing Docker image to Nexus..."

#          docker tag ${{ matrix.service }}:latest your-nexus-repository-url/${{ matrix.service }}:latest
#          docker push your-nexus-repository-url/${{ matrix.service }}:latest
